### ISSUE TITLE
Opyrator launch-ui and launch-api throwing errors

### ISSUE THREAD

**Issue by arsenyturin** [ml-tooling/opyrator#48]
In the fresh environment, using Python 3.9.7 on macOS Monterey 12.2.1 (x86) (tested on M1 chip, same issues)
No extra packages were installed, only Opyrator and its dependencies

The code I'm trying to run:
```python
from pydantic import BaseModel

class Input(BaseModel):
    message: str

class Output(BaseModel):
    message: str

def hello_world(input: Input) -> Output:
    """Returns the `message` of the input data."""
    return Output(message=input.message)
```
### Issue #1
`$ opyrator launch-ui my_opyrator:hello_world`

ModuleNotFoundError: No module named 'streamlit.report_thread'

### Issue #2
`$ opyrator launch-api my_opyrator:hello_world`

ImportError: cannot import name 'graphql' from 'starlette' (/Users/sean/python_envs/opyrator-env/lib/python3.9/site-packages/starlette/__init__.py)

### Problem with streamlit (streamlit==1.6.0)
Some folks on the internet suggest downgrading streamlit, but it seems like the issue still persists.
I've looked into the package itself and didn't find either report_thread.py or "report_thread" in the python files

**Comment by felixmaechtle** [comment]
This seems to be a dependency issue. I got it working with `pip3 install starlette==0.13.6` as a quick fix.

**Comment by edvin-svk** [comment]
+1. One fails on the first thing on "Getting started"...
I downgraded streamlit to 1.3.1 and starlette to 0.13.6 as suggested by @felixmaechtle, now the Getting started works.

**Comment by edvin-svk** [comment]
Can we keep this open until solved?
